Develop
Iordanska/DjangoCarDealership pull request #1
Opened 2023-05-03 16:55 UTC by Iordanska

2023-05-04 08:47 UTC, tosuvs commented on djangopr/dealership/models.py
> +    number_of_buyers = models.IntegerField()
указывай default значение

2023-05-04 08:48 UTC, tosuvs commented on djangopr/dealership/models.py
> +    number_of_buyers = models.IntegerField()
и это поле скорее будет unique_buyers

2023-05-04 08:49 UTC, tosuvs commented on djangopr/dealership/models.py
> +    stock_id = models.IntegerField(unique=True)
это что за поле?

2023-05-04 08:50 UTC, tosuvs commented on djangopr/dealership/models.py
> +    is_active = models.BooleanField(default=True)
is_active, created, updated нужно вынести в миксин

2023-05-04 08:51 UTC, tosuvs commented on djangopr/dealership/models.py
> +
также у тебя нет поля CountryFiled

2023-05-04 08:52 UTC, tosuvs commented on djangopr/dealership/models.py
> +
также не вижу связи с Машинами тут

2023-05-04 08:53 UTC, tosuvs commented on djangopr/dealership/models.py
> +    cars_type = models.CharField(max_length=100)
тип машины должен быть в моделе Car

2023-05-04 08:53 UTC, tosuvs commented on djangopr/dealership/models.py
> +    location = models.CharField(max_length=100)
тут должен быть CountyField

2023-05-04 08:54 UTC, tosuvs commented on djangopr/dealership/models.py
> +    balance = models.FloatField()
Почему float используешь?

2023-05-04 08:54 UTC, tosuvs commented on djangopr/dealership/models.py
> +    balance = models.FloatField()
и тут у тебя может лежать отрицательное значение, чтобы этого не было используй валидаторы

2023-05-04 09:00 UTC, tosuvs commented on djangopr/dealership/models.py
> +    supplier = models.ManyToManyField(Supplier)
посмотри как делаются Many to Many связи, они делаются через промежуточную таблицу где ты можешь добавить ещё филды для какой-то информации

2023-05-04 09:00 UTC, tosuvs commented on djangopr/dealership/models.py
> +    drive_type = models.CharField(max_length=100)
чойсми сделай

2023-05-04 09:01 UTC, tosuvs commented on djangopr/dealership/models.py
> +    engine_type = models.CharField(max_length=100)
тут тоже чойсами

2023-05-04 09:04 UTC, tosuvs commented on djangopr/dealership/models.py
> +    customer_id = models.ForeignKey(CustomerProfile, on_delete=models.CASCADE)
Сделай у Customer и Dealer поле specification которое будет JsonFiled и в нем будут храниться парметры по которым они будут закупать для себя машины

2023-05-04 09:06 UTC, tosuvs commented on djangopr/dealership/models.py
> +    popularity = models.FloatField()
для чего это поле?

2023-05-04 09:09 UTC, tosuvs commented on djangopr/djangopr/settings.py
> +        'NAME': str(os.getenv('DATABASE')),
с getenv оно и так возвращается строкой

2023-05-04 09:10 UTC, tosuvs commented on docker-compose.yml
> +version: '3.1'
старайся использовать последние версии 
насколько я помню 3.9 или 3.8 последняя

2023-05-04 09:10 UTC, tosuvs commented on docker-compose.yml
> +    image: postgres
лучше указывать конкретный image

2023-05-04 09:10 UTC, tosuvs commented on docker-compose.yml
> +    image: postgres
с версией я имею ввиду

2023-05-04 09:11 UTC, tosuvs commented on docker-compose.yml
> +     - '5432:5432'
веб тоже закинь в контейнер, для него тебе будет нужен dockerfile

2023-05-04 09:12 UTC, tosuvs commented on djangopr/dealership/models.py
и как я тебе говорил тебе нужно убрать папку .idea

2023-05-04 09:12 UTC, tosuvs requested changes
comments in PR

2023-05-05 09:42 UTC, tosuvs commented on djangopr/dealership/models.py
> +class TrackableMixin(models.Model):
мне не нравится название
не совсем понятно из название какие он поля хранит

2023-05-05 09:43 UTC, tosuvs commented on djangopr/dealership/models.py
> +    characteristics  = models.JSONField()
у машины как раз лучше сделать характеристики филдами и как я писал до этого некоторые из них буду choice field

2023-05-05 09:47 UTC, tosuvs commented on djangopr/dealership/models.py
> +    specification = models.JSONField()
в спецификацию можешь добавить базовый шаблон
типо:
{
   "model": "",
   "horsepower": "",
   "engine": "",
   и тд
}

2023-05-05 09:48 UTC, tosuvs commented on djangopr/dealership/models.py
> +    balance = MoneyField(max_digits=14, decimal_places=2, default_currency='USD', editable=False)
можно и так, но почитай что такое DecimalFiled и чем он отличается от Float и какие проблемы есть с Float в питоне

2023-05-05 09:51 UTC, tosuvs commented on djangopr/dealership/models.py
> +    quantity = models.PositiveIntegerField(default =0)
добавь в зависимости black и isort и перед тем как коммитить код проходись ими по файлам (кроме файлов миграций и сетингов), и если не знаешь, почитай ещё что такое линтеры и формматеры и в чём разница

2023-05-05 09:51 UTC, tosuvs commented on djangopr/dealership/models.py
> +    quantity = models.PositiveIntegerField(default =0)
либо можешь написать скрипт на прекоммит

2023-05-05 09:53 UTC, tosuvs commented on djangopr/dealership/models.py
> +class SupplierCars(TrackableMixin):
лучше эту модель перенести сразу после модели Supplier чтобы читалось лучше

2023-05-05 09:55 UTC, tosuvs commented on djangopr/dealership/models.py
> +class TrackableMixin(models.Model):
обычно когда у тебя есть несколько апок то лучше выносить в отдельную папку функции модели и другие общие вещи
так как ты потом будешь создавать апку для юзера то лучше сейчас уже вынести в отдельную папку

2023-05-05 10:00 UTC, tosuvs commented on djangopr/dealership/models.py
> +    name = models.CharField(max_length=100)
можешь ещё филдов добваить типо гендер, возраст и тд

2023-05-05 10:05 UTC, tosuvs commented on djangopr/dealership/models.py
> +class Offer(TrackableMixin):
перенести в jsonfield для кастомера

2023-05-05 10:06 UTC, tosuvs commented on djangopr/dealership/models.py
> +    discount_end = models.DateTimeField()
у скидок есть похожие поля, так что можно тоже сделать миксин

2023-05-05 10:06 UTC, tosuvs commented on djangopr/dealership/models.py
> +    discount_end = models.DateTimeField()
и вынести как я уже писал выше в папку

2023-05-05 10:09 UTC, tosuvs commented on djangopr/dealership/models.py
> +    discount_end = models.DateTimeField()
и не нужно начинать название поля с discount потому что у тебя таблица называется discount 
и ты просто можешь поле назвать start_date и тд 
потому что потом при обращении к полю модели будет товтология DealershipDiscount.discount_start

2023-05-05 10:10 UTC, tosuvs commented on djangopr/dealership/models.py
> +class DealershipUniqueCustomers(TrackableMixin):
под это не нужно делать таблицу, так как ты можешь посчитать количество уникальных пользователей по таблице с покупками
можно внутри таблицы Dealership сделать property в котором ты делаешь такую агрегацию запросом

2023-05-05 10:11 UTC, tosuvs commented on djangopr/dealership/models.py
> +
тут пробелов между таблицами много

2023-05-05 10:12 UTC, tosuvs commented on djangopr/dealership/models.py
> +
или это гит так отображает

2023-05-05 10:14 UTC, tosuvs commented on djangopr/dealership/models.py
> +class SupplierSales(TrackableMixin):
у тебя ещё будет история покупок между покупателем и автосалоном, под это тоже должна быть таблица

2023-05-05 10:15 UTC, tosuvs commented on djangopr/dealership/models.py
> +    car_id = models.ForeignKey(Car, on_delete=models.CASCADE)
все foreign_key указываются обычно вначале таблицы

2023-05-05 10:15 UTC, tosuvs commented on djangopr/dealership/models.py
> +    sale_date = models.DateTimeField(auto_now=True)
у тебе в полях миксина есть created поле

2023-05-06 11:28 UTC, Iordanska commented on djangopr/dealership/models.py
> +class DealershipUniqueCustomers(TrackableMixin):
Написано в задании
>Автосалон должен хранить своих уникальных покупателей, которые будут записываться скриптом с соответствующем количеством покупок
 т. е это все-таки в JSON вынести или лучше таблицей?

2023-05-06 11:30 UTC, Iordanska commented on djangopr/dealership/models.py
> +    characteristics  = models.JSONField()
Нужно ли выносить куда-то отдельно валидаторы или списки для choises?

2023-05-08 08:08 UTC, tosuvs commented on djangopr/core/mixins.py
> +    is_active = models.BooleanField(default=True)
ради одного поля не особо вижу смысл делать Миксин, лучше добавь обратно в верхнюю

2023-05-08 08:12 UTC, tosuvs commented on djangopr/dealership/models.py
> +def date_validator(value):
валидаторы тоже вынеси в core

2023-05-08 08:13 UTC, tosuvs commented on djangopr/dealership/models.py
> +    M = "M"
вот пример как сейчас делают чойсы
 ```
class Gender(models.TextChoices):
        M = "Male"
        F = "Female"

sex = models.CharField(choices=Gender.choices, max_length=6)
    
```
  в старых проектах юзали енамы

2023-05-08 08:15 UTC, tosuvs commented on djangopr/dealership/models.py
> +    M = "M"
объявляешь класс и сразу после него поле чтобы потом не приходилось скролить и искать

2023-05-08 08:15 UTC, tosuvs commented on djangopr/dealership/models.py
> +    M = "M"
по такому принципу и остальные чойсы

2023-05-08 08:17 UTC, tosuvs commented on djangopr/dealership/models.py
> +    offer = models.JSONField("Offer", default=offer_default)
лучше назвать order, потому что это не предложение, если мы смотрим со стороны пользователя, а заказ

2023-05-08 08:21 UTC, tosuvs commented on djangopr/dealership/models.py
> +    number_of_purchases_for = models.PositiveIntegerField()
а это что за поле?

2023-05-08 08:21 UTC, tosuvs commented on djangopr/dealership/models.py
> +    primary_client_discount = models.DecimalField(
всё что касается скидок лучше в отдельную таблицу со скидками

2023-05-08 08:22 UTC, tosuvs commented on djangopr/dealership/models.py
> +    supplier_id = models.ForeignKey(Supplier, on_delete=models.CASCADE)
а зачем тут ключ на Поставщика?

2023-05-08 08:23 UTC, tosuvs commented on djangopr/dealership/models.py
> +    supplier_id = models.ForeignKey(Supplier, on_delete=models.CASCADE)
Автосалон может закупать у многих поставщиков

2023-05-08 08:26 UTC, tosuvs commented on djangopr/dealership/models.py
> +    start_date = models.DateTimeField()
поля с датами ниже указываются, обычно как я писал сверху foreign key, потом по логике
в твоём случае это name, description, percent а потом уже даты

2023-05-08 08:26 UTC, tosuvs commented on djangopr/dealership/models.py
> +        return self.pk
тут лучш отображать pk и название

2023-05-08 08:26 UTC, tosuvs commented on djangopr/dealership/models.py
> +        return self.pk
это то что у тебя будет отображаться в Джанго админке

2023-05-08 08:30 UTC, tosuvs commented on djangopr/dealership/models.py
> +
если тут логика как мы обсуждали, что в зависимости от количества покупок ты вытсраиваешь систему с скидок, то тут можно объявить эту градацию, что 5 покупок такая-то скидка и тд

2023-05-08 08:31 UTC, tosuvs commented on djangopr/dealership/models.py
> +
У поставщиков тоже же есть скидки для автосалонов

2023-05-08 08:31 UTC, tosuvs commented on djangopr/dealership/models.py
> +
не вижу этой таблицы

2023-05-09 06:24 UTC, Iordanska commented on djangopr/dealership/models.py
> +    supplier_id = models.ForeignKey(Supplier, on_delete=models.CASCADE)
я исходя из этого делала

2023-05-10 10:41 UTC, merged